#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: j4125-i226 build

on:
  repository_dispatch:
  workflow_dispatch:
permissions:
  contents: write
  actions: write

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt.git
  REPO_BRANCH: master
  CONFIG_FILE: ./config/j4125-i226.config
  UPLOAD_BIN_DIR: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    
    - name: Apt Update
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update

    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        curl -s https://raw.githubusercontent.com/immortalwrt/build-scripts/master/init_build_environment.sh | sudo bash
        sudo apt-get install -y rename pigz libfuse-dev upx subversion clang lua5.1 liblua5.1-0-dev
        sudo apt-get autoremove -y --purge
        sudo apt-get clean
        sudo rm -rf po2lmo
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email ${{ github.actor }}@users.noreply.github.com
        git config --global user.name ${{ github.actor }}
        git config --global init.defaultBranch master
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
    
    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a

    - name: Install feeds
      run: |
        cd openwrt
        ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        set -x
        [ -e $CONFIG_FILE ] && cp -fv $CONFIG_FILE openwrt/.config
        cd openwrt
        sed -i 's/kmod-e1000e //g' target/linux/x86/Makefile
        sed -i 's/kmod-i40e //g' target/linux/x86/Makefile
        sed -i 's/kmod-igb //g' target/linux/x86/Makefile
        sed -i 's/kmod-igbvf //g' target/linux/x86/Makefile
        sed -i 's/kmod-ixgbe //g' target/linux/x86/Makefile
        sed -i 's/kmod-ixgbevf //g' target/linux/x86/Makefile
        sed -i 's/kmod-pcnet32 //g' target/linux/x86/Makefile
        sed -i 's/kmod-tulip //g' target/linux/x86/Makefile
        sed -i 's/kmod-vmxnet3 //g' target/linux/x86/Makefile
        sed -i 's/kmod-r8101 //g' target/linux/x86/Makefile
        sed -i 's/kmod-r8125 //g' target/linux/x86/Makefile
        sed -i 's/kmod-r8126 //g' target/linux/x86/Makefile
        sed -i 's/kmod-r8168 //g' target/linux/x86/Makefile
        sed -i 's/kmod-8139cp //g' target/linux/x86/Makefile
        sed -i 's/kmod-8139too //g' target/linux/x86/Makefile
        sed -i 's/kmod-usb-net //g' target/linux/x86/Makefile
        sed -i 's/kmod-usb-net-asix //g' target/linux/x86/Makefile
        sed -i 's/kmod-usb-net-asix-ax88179 //g' target/linux/x86/Makefile
        sed -i 's/kmod-usb-net-rtl8150 //g' target/linux/x86/Makefile
        sed -i 's/kmod-usb-net-rtl8152-vendor //g' target/linux/x86/Makefile
        sed -i 's/i915-firmware-dmc //g' target/linux/x86/Makefile
        sed -i 's/kmod-amazon-ena //g' target/linux/x86/image/64.mk
        sed -i 's/kmod-amd-xgbe //g' target/linux/x86/image/64.mk
        sed -i 's/kmod-bnx2 //g' target/linux/x86/image/64.mk
        sed -i 's/kmod-e1000 //g' target/linux/x86/image/64.mk
        sed -i 's/kmod-dwmac-intel //g' target/linux/x86/image/64.mk
        sed -i 's/kmod-drm-i915//g' target/linux/x86/image/64.mk
        sed -i 's/kmod-tg3 //g' target/linux/x86/image/64.mk
        sed -i 's/kmod-forcedeth //g' target/linux/x86/image/64.mk
        sed -i 's/dnsmasq-full//g' include/target.mk
        make defconfig
        cat .config | grep -v -E '^#|^$'

    - name: Download package
      id: package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DEVICE_NAME=_generic" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Organize files
      id: organize
      run: |
        cd openwrt/bin/targets/*/*
        ls -al *
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: mt7986a${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true'
      run: |
        echo "release_tag=v$(date +"%Y.%m.%d.%H%M")/j4125-i226/basic" >> $GITHUB_OUTPUT
        touch release.txt
        echo "j4125-i226 firmware" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v2.1.0
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ steps.tag.outputs.release_name }}
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: |
         ${{ env.FIRMWARE }}/*.ubi
         ${{ env.FIRMWARE }}/*.bin
         ${{ env.FIRMWARE }}/*.manifest

    - name: Delete releases and workflows runs
      uses: ophub/delete-releases-workflows@main
      with:
        delete_workflows: true
        workflows_keep_day: 3
        gh_token: ${{ secrets.GITHUB_TOKEN }}
