#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: s20p build

on:
  repository_dispatch:
  workflow_dispatch:
permissions:
  contents: write
  actions: write

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-6.6.git
  REPO_BRANCH: openwrt-24.10-6.6
  CONFIG_FILE: ./config/s20p.config
  DTS_FILE: ./dts/mt7986a-supergateway-s20p.dts
  UPLOAD_BIN_DIR: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    
    - name: Apt Update
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update

    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        curl -s https://raw.githubusercontent.com/immortalwrt/build-scripts/master/init_build_environment.sh | sudo bash
        sudo apt-get install -y rename pigz libfuse-dev upx subversion clang lua5.1 liblua5.1-0-dev
        sudo apt-get autoremove -y --purge
        sudo apt-get clean
        sudo rm -rf po2lmo
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email ${{ github.actor }}@users.noreply.github.com
        git config --global user.name ${{ github.actor }}
        git config --global init.defaultBranch master
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
    
    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Update feeds
      run: |
        cd openwrt
        cd package
        git clone https://github.com/stevenjoezhang/luci-app-adguardhome.git -b dev
        cd ..
        ./scripts/feeds update -a

    - name: Install feeds
      run: |
        cd openwrt
        ./scripts/feeds install -a

    - name: Strip wifi&usb
      run: |
        set -x
        [ -e $DTS_FILE ] && cp -fv $DTS_FILE openwrt/target/linux/mediatek/dts/
        cd openwrt
        sed -i -e '/s20p/ { n; N; d }' target/linux/mediatek/filogic/base-files/etc/board.d/01_leds

    - name: Load custom configuration
      run: |
        set -x
        [ -e $CONFIG_FILE ] && cp -fv $CONFIG_FILE openwrt/.config
        cd openwrt
        cp -fv defconfig/mt7986-nowifi.config .config
        sed -i 's/s20m/s20p/g' .config
        sed -i '/CONFIG_PACKAGE_nano/d' .config
        sed -i '/CONFIG_PACKAGE_openssh-sftp-server/d' .config
        sed -i '/CONFIG_PACKAGE_luci-app-wrtbwmon/d' .config
        sed -i '/CONFIG_PACKAGE_libpcap/d' .config
        sed -i '/CONFIG_PACKAGE_tcpdump/d' .config
        sed -i '/eqos-mtk/d' .config
        sed -i '/mtkhqos_util/d' .config
        echo "CONFIG_PACKAGE_luci-app-adguardhome=y" >> .config
        echo "CONFIG_PACKAGE_luci-theme-argon=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-adguardhome-zh-cn=y" >> .config
        make defconfig
        cat .config | grep -v -E '^#|^$'

    - name: Download package
      id: package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DEVICE_NAME=_supergateway_s20p" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Organize files
      id: organize
      run: |
        cd openwrt/bin/targets/*/*
        ls -al *
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: mt7986a${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true'
      run: |
        echo "release_tag=v$(date +"%Y.%m.%d.%H%M")/s20p/basic" >> $GITHUB_OUTPUT
        touch release.txt
        echo "S20P firmware" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v2.1.0
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ steps.tag.outputs.release_name }}
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: |
         ${{ env.FIRMWARE }}/*.ubi
         ${{ env.FIRMWARE }}/*.bin
         ${{ env.FIRMWARE }}/*.manifest

    - name: Delete releases and workflows runs
      uses: ophub/delete-releases-workflows@main
      with:
        delete_workflows: true
        workflows_keep_day: 3
        gh_token: ${{ secrets.GITHUB_TOKEN }}
